aws:
  region: us-east-1
  bucket-name: pastebin-files-bucket

server:
  port: 8083

spring:
  rabbitmq:
    addresses: localhost:5672


rabbitmq:
  exchanges:
    s3:
      name: paste-s3-exchange
  queues:
    s3-create: paste-s3-sender
    s3-delete: paste-s3-cleaner
  routing-keys:
    create: paste-s3-creation-routing-key
    delete: paste-s3-deletion-routing-key