aws:
  region: us-east-1
  bucket-name: pastebin-files-bucket
  key:

server:
  port: 8083

spring:
  rabbitmq:
    addresses: localhost:5672


rabbitmq:
  exchange:
    name: paste-s3-exchange
  queue:
    name: paste-s3-sender
  routing-key:
    name: paste-s3-routing-key