aws:
  region: us-east-1
  bucket-name: pastebin-files-bucket
  key:

server:
  port: 8083

spring:
  rabbitmq:
    addresses: localhost:5672


rabbitmq:
  exchange: paste.files
  queue: paste.sender
  routing-key: paste_to_s3_routing-key