server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/paste-analytics
    username: postgres
    password: password
  rabbitmq:
    addresses: localhost:5672


  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update

rabbitmq:
  exchanges:
    paste-analytics: paste-analytics-exchange
  queues:
    info-create:
      name: paste-info-creation-queue
    info-delete:
      name: paste-info-deletion-queue
  routing-keys:
    info-create:
      name: paste-to-paste-info-creation-routing-key
    info-delete:
      name: paste-to-paste-info-deletion-routing-key
